const $=x=>document.getElementById(x);let db,banks=[],stats={},marks=[],history=[],current,pool=[],quiz=[],i=0,score=0,wrong=[],timer,answered=false,finishing=false;
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));const today=()=>new Date().toISOString().slice(0,10);
function openDB(){return new Promise((ok,fail)=>{let r=indexedDB.open('UPSC_ACTIVE_RECALL_V3',1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('d'))d.createObjectStore('d')};r.onsuccess=()=>{db=r.result;db.onversionchange=()=>db.close();ok()};r.onerror=()=>fail(r.error||new Error('Could not open local database.'))})}
function get(k,d){return new Promise((ok,fail)=>{try{let r=db.transaction('d','readonly').objectStore('d').get(k);r.onsuccess=()=>ok(r.result??d);r.onerror=()=>fail(r.error||new Error('Could not read local data.'))}catch(e){fail(e)}})}
function put(k,v){return new Promise((ok,fail)=>{try{let tx=db.transaction('d','readwrite'),r=tx.objectStore('d').put(v,k);r.onsuccess=()=>ok();r.onerror=()=>fail(r.error||new Error('Could not save local data.'));tx.onerror=()=>fail(tx.error||new Error('Could not save local data.'))}catch(e){fail(e)}})}
const all=()=>banks.flatMap(b=>b.questions.map(q=>({...q,subject:q.subject||b.subject,book:q.book||b.book,chapter:q.chapter||b.chapter})));const due=q=>!stats[q.id]?.nextReview||stats[q.id].nextReview<=today();
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');scrollTo(0,0)}function home(){show('home');render()}
async function init(){banks=await get('banks',[]);stats=await get('stats',{});marks=await get('marks',[]);history=await get('history',[]);render()}
function render(){let term=$('search').value.toLowerCase(),qs=all(),map={};banks.forEach(b=>{let s=b.subject||'General',c=b.chapter||b.name;map[s]??={};map[s][c]=(map[s][c]||0)+b.questions.length});let h='';for(let s in map){if(term&&!s.toLowerCase().includes(term)&&!Object.keys(map[s]).some(c=>c.toLowerCase().includes(term)))continue;h+=`<div class="subject"><b>📚 ${esc(s)}</b><span class="count">${Object.values(map[s]).reduce((a,b)=>a+b,0)}</span>`;for(let c in map[s])h+=`<div class="chapter" data-s="${esc(s)}" data-c="${esc(c)}">📖 ${esc(c)} <span class="count">${map[s][c]}</span></div>`;h+='</div>'}$('subjectTree').innerHTML=h||'<p class="muted">No matching banks.</p>';document.querySelectorAll('.chapter').forEach(x=>x.onclick=()=>openChapter(x.dataset.s,x.dataset.c));$('dueCount').textContent=qs.filter(due).length;$('wrongCount').textContent=qs.filter(q=>stats[q.id]?.wrong>0).length;$('markCount').textContent=marks.length;$('testCount').textContent=history.length+' tests'}
function openChapter(s,c){let q=all().filter(x=>x.subject===s&&x.chapter===c);current={name:`${s} — ${c}`,questions:q,subject:s,chapter:c};$('chapterTitle').textContent=c;$('chapterSub').textContent=`${s} • ${q.length} questions`;let t={};q.forEach(x=>t[x.topic||'Unspecified']=(t[x.topic||'Unspecified']||0)+1);$('topics').innerHTML=Object.entries(t).map(([k,n])=>`<div class="topic" data-topic="${esc(k)}">🎯 ${esc(k)} <span class="count">${n}</span></div>`).join('');document.querySelectorAll('.topic').forEach(x=>x.onclick=()=>setup(q.filter(y=>(y.topic||'Unspecified')===x.dataset.topic),`${s} — ${c} — ${x.dataset.topic}`));$('chapterTest').onclick=()=>setup(q,`${s} — ${c}`);$('deleteChapter').onclick=()=>deleteChapter(s,c);show('chapter')}
function setup(q,name){pool=[...q];current={name,questions:pool};$('setupTitle').textContent=name;$('setupSub').textContent=pool.length+' questions';show('setup')}
function start(){let p=[...pool],d=$('difficulty').value;if(d!=='all')p=p.filter(q=>(q.difficulty||'').toLowerCase()===d.toLowerCase());if($('selection').value==='random')p.sort(()=>Math.random()-.5);if($('selection').value==='weak')p.sort((a,b)=>(stats[b.id]?.wrong||0)-(stats[a.id]?.wrong||0));if(!p.length)return alert('No questions match this filter.');quiz=p;i=0;score=0;wrong=[];finishing=false;show('quiz');startTimer();renderQ()}
function startTimer(){clearInterval(timer);let s=+$('timer').value*60;$('clock').textContent='';if(!s)return;$('clock').textContent=`⏱ ${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;timer=setInterval(()=>{s--;if(s<=0){clearInterval(timer);timer=null;$('clock').textContent='⏱ 0:00';finish();return}$('clock').textContent=`⏱ ${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`},1000)}
function renderQ(){let q=quiz[i];if(!q){finish();return}answered=false;$('progress').textContent=`Q ${i+1}/${quiz.length}`;$('score').textContent=`Score ${score}`;$('meta').textContent=[q.subject,q.book,q.chapter,q.topic,q.difficulty,q.source].filter(Boolean).join(' • ');$('question').textContent=q.question;$('feedback').classList.add('hidden');$('next').classList.add('hidden');$('bookmark').textContent=marks.includes(q.id)?'★ Bookmarked':'☆ Bookmark';$('options').innerHTML='';const opts=Array.isArray(q.options)?q.options.reduce((o,v,n)=>(o[String.fromCharCode(65+n)]=v,o),{}):(q.options||{});Object.entries(opts).forEach(([k,v])=>{let b=document.createElement('button');b.className='option';b.textContent=k+'. '+v;b.onclick=()=>answer(k);$('options').appendChild(b)})}
async function answer(k){if(answered||finishing)return;answered=true;let q=quiz[i],ok=k===q.answer;if(ok)score++;else wrong.push(q);let s=stats[q.id]||{attempts:0,correct:0,wrong:0,streak:0,interval:0};s.attempts++;s[ok?'correct':'wrong']++;s.streak=ok?s.streak+1:0;s.interval=ok?(s.interval?Math.min(Math.round(s.interval*2.2),180):1):0;s.nextReview=new Date(Date.now()+s.interval*86400000).toISOString().slice(0,10);stats[q.id]=s;try{await put('stats',stats)}catch(e){console.warn('Stats save failed:',e)}[...$('options').children].forEach((b,n)=>{let key=String.fromCharCode(65+n);b.disabled=true;if(key===q.answer)b.classList.add('correct');if(key===k&&!ok)b.classList.add('wrong')});let oa=q.option_analysis||'',a=typeof oa==='string'?`<div>${esc(oa)}</div>`:Object.entries(oa).map(([x,v])=>`<div><b>${esc(x)}:</b> ${esc(v)}</div>`).join('');$('feedback').innerHTML=`<b>${ok?'✅ Correct':'❌ Incorrect'}</b>${ok?'':'<p><b>Correct answer: '+esc(q.answer)+'</b></p>'}<p><b>Explanation:</b> ${esc(q.explanation||'')}</p>${a?'<hr><b>Option analysis</b>'+a:''}${q.upsc_trap?'<hr><b>⚠ UPSC Trap:</b> '+esc(q.upsc_trap):''}${q.memory_hook?'<hr><b>🧠 Memory Hook:</b> '+esc(q.memory_hook):''}${q.key_fact?'<hr><b>📌 Key Fact:</b> '+esc(q.key_fact):''}${q.linkage?'<hr><b>🔗 Linkage:</b> '+esc(q.linkage):''}`;$('feedback').classList.remove('hidden');$('next').classList.remove('hidden')}function nextQ(){if(finishing||!answered)return;i++;i<quiz.length?renderQ():finish()}
async function finish(){if(finishing)return;finishing=true;clearInterval(timer);timer=null;if(!quiz.length){finishing=false;home();return}let pct=Math.round(score/quiz.length*100);history.unshift({date:new Date().toISOString(),name:current?.name||'Test',total:quiz.length,correct:score,pct});history=history.slice(0,200);try{await put('history',history)}catch(e){console.warn('History save failed:',e)}let m={};wrong.forEach(q=>m[q.topic||'Unspecified']=(m[q.topic||'Unspecified']||0)+1);$('resultStats').innerHTML=`<div class="big">${pct}%</div><p>Correct: <b>${score}</b> / ${quiz.length}</p><p>Wrong: <b>${quiz.length-score}</b></p>`;$('weak').innerHTML=Object.entries(m).map(([k,n])=>`<li>${esc(k)} — ${n} wrong</li>`).join('')||'<li>No weak topics 🎉</li>';show('result')}
async function bookmark(){let id=quiz[i].id;marks=marks.includes(id)?marks.filter(x=>x!==id):[...marks,id];await put('marks',marks);renderQ();render()}
function revision(type){let q=all(),p=type==='wrong'?q.filter(x=>stats[x.id]?.wrong>0):type==='marked'?q.filter(x=>marks.includes(x.id)):q.filter(due);if(!p.length)return alert('Nothing to revise.');setup(p,type==='wrong'?'Wrong Questions':type==='marked'?'Bookmarks':'Due Review')}
async function deleteChapter(s,c){
  const targets=banks.filter(b=>(b.subject||'General')===s&&(b.chapter||b.name)===c);
  if(!targets.length){showDeleteMessage('Delete failed','This chapter/question bank is no longer in local storage. Refresh the app and try again.');return;}
  const count=targets.reduce((n,b)=>n+(Array.isArray(b.questions)?b.questions.length:0),0);
  const names=targets.map(b=>b.name||`${s} — ${c}`).join(', ');
  showDeleteConfirm(`${s} — ${c}`, count, async()=>{
    try{
      const ids=new Set(targets.flatMap(b=>(b.questions||[]).map(q=>q.id).filter(Boolean)));
      const targetIds=new Set(targets.map(b=>b.id).filter(Boolean));
      // Remove exactly the bank(s) represented by this chapter screen.
      banks=banks.filter(b=>!targets.includes(b) && !targetIds.has(b.id));
      const newStats={};
      Object.keys(stats||{}).forEach(id=>{if(!ids.has(id))newStats[id]=stats[id]});
      stats=newStats;
      marks=(marks||[]).filter(id=>!ids.has(id));
      // Save all related stores before changing screens.
      await Promise.all([put('banks',banks),put('stats',stats),put('marks',marks)]);
      current=null;pool=[];quiz=[];wrong=[];answered=false;finishing=false;
      closeDeleteModal();
      render();
      show('home');
      showDeleteMessage('Deleted successfully',`${names}\n\n${count} questions were removed from this PWA.\n\nYour original JSON file and GitHub copy are untouched.`);
    }catch(e){
      console.error('Delete failed:',e);
      showDeleteMessage('Delete failed',`The bank could not be deleted.\n\n${e?.message||e}`);
    }
  });
}
function showDeleteConfirm(name,count,onConfirm){
  closeDeleteModal();
  const wrap=document.createElement('div');
  wrap.id='deleteModal';
  wrap.className='modalOverlay';
  wrap.innerHTML=`<div class="modalCard"><h2>🗑 Delete Question Bank?</h2><p><b>${esc(name)}</b></p><p>${count} questions will be removed from this PWA.</p><p class="muted">Your original JSON/GitHub copy will NOT be deleted.</p><div class="modalActions"><button id="deleteConfirm" class="danger">Yes, Delete</button><button id="deleteCancel" class="secondary">Cancel</button></div></div>`;
  document.body.appendChild(wrap);
  $('deleteCancel').onclick=closeDeleteModal;
  $('deleteConfirm').onclick=async()=>{const b=$('deleteConfirm');b.disabled=true;b.textContent='Deleting…';await onConfirm();};
}
function showDeleteMessage(title,msg){
  closeDeleteModal();
  const wrap=document.createElement('div');wrap.id='deleteModal';wrap.className='modalOverlay';
  wrap.innerHTML=`<div class="modalCard"><h2>${esc(title)}</h2><p style="white-space:pre-line">${esc(msg)}</p><button id="deleteOk">OK</button></div>`;
  document.body.appendChild(wrap);$('deleteOk').onclick=closeDeleteModal;
}
function closeDeleteModal(){const m=document.getElementById('deleteModal');if(m)m.remove();}

async function importBank(file){try{let d=JSON.parse(await file.text());if(!Array.isArray(d.questions))throw Error('JSON must contain questions array.');d.name=d.name||`${d.subject||'General'} — ${d.chapter||'Bank'}`;d.id=d.id||('BANK-'+btoa(unescape(encodeURIComponent(d.subject||'General'+'|'+d.chapter+'|'+d.name))).replace(/[^A-Za-z0-9]/g,'').slice(0,40));d.questions.forEach((q,n)=>{q.id=q.id||d.id+'-'+(n+1);q.subject=q.subject||d.subject;q.book=q.book||d.book;q.chapter=q.chapter||d.chapter});let n=banks.findIndex(x=>x.id===d.id||x.name===d.name);n>=0?banks[n]=d:banks.push(d);await put('banks',banks);render();alert(`Imported ${d.questions.length} questions.`)}catch(e){alert('Import failed: '+e.message)}}
function backup(){let d={format:'UPSC_ACTIVE_RECALL_V3',version:3,exportedAt:new Date().toISOString(),banks,stats,marks,history},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='UPSC_Active_Recall_V3_Backup.json';a.click()}
function restore(){let f=document.createElement('input');f.type='file';f.accept='.json';f.onchange=async()=>{try{let d=JSON.parse(await f.files[0].text());if(d.format!=='UPSC_ACTIVE_RECALL_V3')throw Error('Not a V3 backup.');banks=d.banks||[];stats=d.stats||{};marks=d.marks||[];history=d.history||[];await put('banks',banks);await put('stats',stats);await put('marks',marks);await put('history',history);alert('Backup restored.');render()}catch(e){alert(e.message)}};f.click()}
function showHistory(){let q=all(),a=q.filter(x=>stats[x.id]?.attempts),att=a.reduce((n,x)=>n+stats[x.id].attempts,0),cor=a.reduce((n,x)=>n+stats[x.id].correct,0);$('performance').innerHTML=`<p><b>Total questions:</b> ${q.length}</p><p><b>Questions attempted:</b> ${a.length}</p><p><b>Total attempts:</b> ${att}</p><p><b>Overall accuracy:</b> ${att?Math.round(cor/att*100):0}%</p><h3>Recent tests</h3>`+(history.length?history.slice(0,20).map(h=>`<div class="historyRow"><b>${esc(h.name)}</b><br>${new Date(h.date).toLocaleString()}<br>${h.correct}/${h.total} correct — <b>${h.pct}%</b></div>`).join(''):'<p class="muted">No tests yet.</p>');show('history')}
$('search').oninput=render;$('fileInput').onchange=e=>e.target.files[0]&&importBank(e.target.files[0]);$('backupBtn').onclick=backup;$('restoreBtn').onclick=restore;$('back').onclick=home;$('cancel').onclick=home;$('start').onclick=start;$('next').onclick=nextQ;$('bookmark').onclick=bookmark;$('retry').onclick=()=>revision('wrong');$('resultHome').onclick=home;$('historyHome').onclick=home;$('backupBtn').onclick=backup;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='history')showHistory();else if(a==='all')setup(all(),'All Questions');else revision(a)});openDB().then(init);if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).catch(e=>console.warn('SW registration failed:',e));}